Repository bitwarden/jslib, pull requests merged in 2020-08, with the labels that each got.

#139 [SSO] Merge feature/sso into master
  src/abstractions/api.service.ts
  src/angular/components/change-password.component.ts
  src/angular/components/sso.component.ts
  src/angular/components/two-factor.component.ts
  src/models/request/setPasswordRequest.ts
  src/services/api.service.ts
Labels: enhancement

#124 Bug.568.organization search ignores custom fields
  src/services/search.service.ts
Labels: bug

#144 [SSO] Login - added launchSsoBrowser method
  src/angular/components/login.component.ts
Labels: enhancement

#146 Misc jslib cleanups
  src/abstractions/index.ts
  src/angular/components/login.component.ts
Labels: invalid

#145 Merge plan and price updates
  src/abstractions/api.service.ts
  src/enums/planType.ts
  src/enums/productType.ts
  src/models/response/organizationResponse.ts
  src/models/response/planResponse.ts
  src/services/api.service.ts
Labels: enhancement

#156 [SSO] Bug - Fixed set password route
  src/angular/components/two-factor.component.ts
Labels: bug

#159 [SSO] Set Password flow sync
  src/angular/components/set-password.component.ts
  src/cli/commands/login.command.ts
Labels: enhancement
